# Generated by Django 5.0.9 on 2024-11-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(choices=[('PENDING', 'В ожидании'), ('APPROVED', 'Одобренный'), ('REJECTED', 'Отклоненный')], default='PENDING', max_length=16),
        ),
    ]
