# Generated by Django 5.0.9 on 2024-11-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_record_comment_alter_record_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
